# Generated by Django 5.1.6 on 2025-04-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='senha',
        ),
    ]
