# Generated by Django 5.2 on 2025-05-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0002_remove_aluno_email_remove_aluno_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta_1', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_2', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('pergunta_3', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('sugestao', models.CharField(max_length=100)),
            ],
        ),
    ]
