# Generated by Django 5.1.6 on 2025-05-16 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0005_eventocalendario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesempenhoFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faltas', models.IntegerField()),
                ('desempenho', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='🙂', max_length=5)),
                ('comentario_professor', models.TextField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.aluno')),
            ],
        ),
    ]
