# Generated by Django 5.1.6 on 2025-05-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0006_desempenhofrequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desempenhofrequencia',
            name='comentario_professor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
