# Generated by Django 5.1.6 on 2025-05-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0007_alter_desempenhofrequencia_comentario_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desempenhofrequencia',
            name='desempenho',
        ),
        migrations.AlterField(
            model_name='desempenhofrequencia',
            name='emoji',
            field=models.CharField(max_length=5),
        ),
    ]
