# Generated by Django 5.1.6 on 2025-05-19 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0008_remove_desempenhofrequencia_desempenho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desempenhofrequencia',
            name='aluno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.aluno'),
        ),
    ]
