# Generated by Django 5.1.6 on 2025-05-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0009_alter_desempenhofrequencia_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocalendario',
            name='descricao',
        ),
        migrations.AddField(
            model_name='eventocalendario',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
